version: '3'
services:
  test:
# docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean test    
    image: "maven:3.3-jdk-8"
    volumes:
      - ./:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    command: mvn clean test surefire-report:report

# volumes: 
  # mymaven:

#  redis:
#    image: "redis:alpine"

#Available lifecycle phases are: 
#validate
#initialize
#generate-sources
#process-sources
#generate-resources
#process-resources
#compile
#process-classes 
#generate-test-sources
#process-test-sources, generate-test-resources, process-test-resources, 
#test-compile
#process-test-classes, test, prepare-package, package, 
#pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy
